In [3]:
import numpy as np


In [4]:
# 1

vector1 = np.zeros(10)
vector1[4] = 1

print(vector1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
#2

vector2 = np.arange(10, 50)

print(vector2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
#3

matrix = np.arange(9)
matrix = matrix.reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
#4

array4 = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(array4)

print(indices)

(array([0, 1, 4], dtype=int32),)


In [11]:
#5

array5 = np.random.rand(10, 10)

minimum_value = np.min(array5)
maximum_value = np.max(array5)

print("Minimum value:", minimum_value)
print("Maximum value:", maximum_value)

Minimum value: 0.004378825687862409
Maximum value: 0.9861726027716258


In [10]:
#6


vector6 = np.random.rand(30)

mean_value = np.mean(vector6)

print("Mean value:", mean_value)

Mean value: 0.5009867852633977
